version: '3'
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432

  finance-db:
    image: postgres:11
    container_name: finance-db
    restart: always
    environment:
      - POSTGRES_DB=finance-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - 5433:5432
      
  finance_rabbit:
    image: rabbitmq:3-management
    container_name: finance_rabbit
    hostname: finance_rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
