server:
  port: ${PORT:8081}

spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: product-api

# WITHOUT-DOCKER
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financedb
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

#  WITH-DOCKER
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:data-finance-db}
#    username: ${DB_USER:admin}
#    password: ${DB_PASSWORD:root}
#    initialization-mode: always
#    initialize: true
#    continue-on-error: true
#    platform: postgresql
#    maxActive: 3

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      format_sql: true
#    show_sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect

## PROD
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://svr-taurus.database.windows.net:1433;database=taurus-bd;user=admin-taurus@svr-taurus;password=#Gfgrupo4;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
#    show-sql: true


file:
  upload-dir: . /Code/UploadDir